version: 2

models:

  # ============================================================
  # ACCOUNT
  # ============================================================
  - name: stg_account
    description: "Filtered GWPC account source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_account_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC account public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # CONTACT
  # ============================================================
  - name: stg_contact
    description: "Filtered GWPC contact source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_contact_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC contact public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # POLICY
  # ============================================================
  - name: stg_policy
    description: "Filtered GWPC policy source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_policy_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC policy public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # ACCOUNT CONTACT
  # ============================================================
  - name: stg_accountcontact
    description: "GWPC account-contact relationship source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_accountcontact_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC account-contact relationship public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # ACCOUNT CONTACT ROLE
  # ============================================================
  - name: stg_accountcontactrole
    description: "GWPC account-contact-role relationship source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_accountcontactrole_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC account-contact-role relationship public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # POLICY CONTACT ROLE
  # ============================================================
  - name: stg_policycontactrole
    description: "GWPC policy-contact-role relationship source."

    tests:
      - reconciliation_source_staging:
          arguments:
            source_table: "{{ source('gwpc', 'pc_policycontactrole_curr') }}"
            source_key: publicid
            staging_key: publicid

    columns:
      - name: publicid
        description: "GWPC policy-contact-role relationship public identifier."
        tests:
          - not_null
          - unique


  # ============================================================
  # POLICY PERIOD
  # ============================================================
  - name: stg_policyperiod
    description: "Filtered GWPC policy period source."

    columns:
      - name: publicid
        description: "GWPC policy period public identifier."
        tests:
          - not_null
          - unique
  
  - name: hub_account
    description: "Data Vault Hub for GWPC accounts."

    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_account
            staging_key: publicid
            hub_key: account_hk
            hub_business_key: source_system_unique_identifier
            source_system: GWPC
            
  - name: hub_contact
    description: "Data Vault Hub for GWPC contacts."

    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_contact
            staging_key: publicid
            hub_key: contact_hk
            hub_business_key: source_system_unique_identifier
            source_system: GWPC
  
  - name: hub_policy
    description: "Data Vault Hub for GWPC policies."

    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_policy
            staging_key: policynumber
            hub_key: policy_hk
            hub_business_key: policy_number
            source_system: GWPC            