version: 2

models:

  - name: hub_account
    description: "Raw Vault Account Hub."
    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_account
            staging_key: publicid
            hub_key: account_hk
            hub_business_key: source_system_unique_identifier
            source_system: GWPC
    columns:
      - name: account_hk
        tests: [not_null, unique]
      - name: source_system_unique_identifier
        tests: [not_null]
      - name: account_number
        tests: [not_null]
      - name: source_system_name
        tests: [not_null]
      - name: load_dts
        tests: [not_null]

  - name: hub_contact
    description: "Raw Vault Contact Hub."
    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_contact
            staging_key: publicid
            hub_key: contact_hk
            hub_business_key: source_system_unique_identifier
            source_system: GWPC
    columns:
      - name: contact_hk
        tests: [not_null, unique]
      - name: source_system_contact_identifier
        tests: [not_null]
      - name: source_system_unique_identifier
        tests: [not_null]
      - name: source_system_name
        tests: [not_null]
      - name: load_dts
        tests: [not_null]

  - name: hub_policy
    description: "Raw Vault Policy Hub."
    tests:
      - reconciliation_staging_hub:
          arguments:
            staging_model: stg_policy
            staging_key: policynumber
            hub_key: policy_hk
            hub_business_key: policy_number
            source_system: GWPC
    columns:
      - name: policy_hk
        tests: [not_null, unique]
      - name: source_system_unique_identifier
        tests: [not_null]
      - name: policy_number
        tests: [not_null]
      - name: term_number
        tests: [not_null]
      - name: source_system_name
        tests: [not_null]
      - name: load_dts
        tests: [not_null]